FROM {{ image }}

MAINTAINER Rob McQueen

# Install Ansible prerequisites
{% if family == "Debian" %}
RUN apt-get update && apt-get install -y \
  build-essential \
  libffi-dev \
  libyaml-dev \
  libssl-dev \
  python-dev \
  python-virtualenv \
  sudo
{% elif family == "RedHat" %}
RUN yum install -y \
  gcc \
  libffi-devel \
  libyaml-devel \
  openssl-devel \
  epel-release \
  python-pip \
  python-virtualenv \
  sudo
{% else %}
RUN echo "OS family {{ family }} not yet supported, try adding it to Dockerfile.j2" ; exit 1
{% endif %}

# Install Ansible
RUN mkdir /opt/ansible && virtualenv /opt/ansible/venv && \
  . /opt/ansible/venv/bin/activate  && \
  pip install --upgrade setuptools && \ 
  pip install ansible 

ADD . /build
COPY .ansible-test /build
WORKDIR /build

CMD . /opt/ansible/venv/bin/activate && ansible-playbook -i inventory.yml \
    -c local -s -e testing=true -e role=$DOCKER_TEST_ROLE \
    {{ extra_args| join(" ") }} playbook.yml; /bin/bash
